# Generated by Django 4.2.13 on 2024-05-15 02:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('buslines', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('customer', django.db.models.manager.Manager()),
            ],
        ),
    ]
