# Generated by Django 4.2.13 on 2024-05-13 11:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buslines', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslines.driver')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('travel_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buslines.buses')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslines.category')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
