# Generated by Django 4.2.13 on 2024-05-15 06:43

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('buslines', '0003_alter_customer_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerProfile',
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='DriverProfile',
        ),
        migrations.RenameModel(
            old_name='Driver',
            new_name='SellerProfile',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buslines.user',),
            managers=[
                ('customer', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buslines.user',),
            managers=[
                ('driver', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buslines.user',),
            managers=[
                ('seller', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customerprofile',
            managers=[
            ],
        ),
    ]
