# Generated by Django 4.2.13 on 2024-05-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buslines', '0005_sellerprofile_note_alter_buses_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslines.driverprofile'),
        ),
    ]
